chronicles/urls.py
from django.urls import path
from . import views
from .feeds import PostFeed

app_name = "chronicles"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("feed/", PostFeed(), name="post_feed"),
]

donquixote_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from chronicles.sitemaps import PostSitemap


sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("chronicles/", include("chronicles.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

chronicles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        PUBLISHED = "PB", "Published"
        DRAFT = "DF", "Draft"

    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250,
        unique_for_date="publish",
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="chronicles_posts",
    )
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "chronicles:post_detail",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ],
        )

    tags = TaggableManager()


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    name = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"]),
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

chronicles/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]

chronicles/views.py
# Django Core
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.core.mail import send_mail
from django.views.decorators.http import require_POST

# Third-Party package
from taggit.models import Tag

# Local apps impots
from .forms import EmailPostForm, CommentForm
from .models import Post


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    # Pagination with 3 post per page.
    paginator = Paginator(post_list, 3)
    page_num = request.GET.get("page", 1)

    try:
        page_obj = paginator.page(page_num)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        page_obj = paginator.page(1)

    return render(
        request,
        "chronicles/post_list.html",
        {
            "posts": page_obj,
            "tag": tag,
        },
    )


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=slug,
    )
    comments = post.comments.filter(active=True)

    form = CommentForm()

    # List of similar post
    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]

    return render(
        request,
        "chronicles/post_detail.html",
        {
            "post": post,
            "similar_posts": similar_posts,
            "comments": comments,
            "form": form,
        },
    )


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post.published, id=post_id)
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    return render(
        request,
        "chronicles/post_comment.html",
        {
            "post": post,
            "comment": comment,
            "form": form,
        },
    )


def post_share(request, post_id):
    post = get_object_or_404(Post.published, id=post_id)
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} te recomienda: {post.title}"

            message = (
                f"Hola,\n\n"
                f"{cd['name']} ({cd['email']}) quiere compartir contigo este post:\n"
                f"{post.title}\n{post_url}\n\n"
                f"Comentarios:\n{cd['comments']}\n\n"
                "Saludos,"
            )
            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[cd["to"]],
            )
            sent = True

    else:
        form = EmailPostForm()

    return render(
        request,
        "chronicles/post_share.html",
        {
            "form": form,
            "post": post,
            "sent": sent,
        },
    )

templates/_base.html
{% load static %}
{% load chronicles_extras %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
                Donquixote Family
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="{% static 'css/chronicles.css' %}">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
        <div id="sidebar">
            <h2>Donquixote Family</h2>
            <p>¡Los que están en la cima determinan lo que está bien y lo que está mal!</p>
            <p>Published post: {% get_post_count %}</p>
            <h3>Latest Post</h3>
            {% get_latest_posts 3 %}
            <h3>Most commented posts</h3>
            {% get_most_commented_posts as most_commented_posts %}
            <ul>
                {% for post in most_commented_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>

templates/chronicles/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/chronicles/post_comment.html
{% extends "_base.html" %}
{% block title %}
{% endblock title %}
{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p>
            <a href="{{ post.get_absolute_url }}">Back to the post.</a>
        </p>
    {% else %}
        {% include "includes/comment_form.html" %}
    {% endif %}
{% endblock content %}

templates/chronicles/post_detail.html
{% extends '_base.html' %}
{% load chronicles_extras %}
{% block title %}
    Donquixote Note {{ post.title }}
{% endblock title %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "chronicles:post_share" post.id %}">Share this post</a>
    </p>
    <h2>Similar Posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}
    <p>
        Tags:
        {% for tag in post.tags.all %}
            <a href="{% url 'chronicles:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %},{% endif %}
        {% endfor %}
    </p>
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments.</p>
    {% endfor %}
    {% include "includes/comment_form.html" %}
{% endblock content %}

templates/chronicles/post_list.html
{% extends '_base.html' %}
{% load chronicles_extras %}
{% block title %}
    Donquixote Chronicles
{% endblock title %}
{% block content %}
    <h1>Donquixote Family Chronicles</h1>
    {% if tag %}<h2>Posts tagged with {{ tag.name }}</h2>{% endif %}
    {% for post in posts %}
        <article>
            <h2>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h2>
            <p>
                Tags:
                {% for tag in post.tags.all %}
                    <a href="{% url 'chronicles:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                    {% if not forloop.last %},{% endif %}
                {% endfor %}
            </p>
            <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
            <div>{{ post.body|markdown|truncatewords_html:30 }}</div>
        </article>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock content %}

templates/chronicles/post_share.html
{% extends "_base.html" %}
{% block title %}
    Share a post
{% endblock title %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}</p>
    {% else %}
        <h1>Share {{ post.title }} by e-mail</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock content %}

templates/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "chronicles:post_comment" post.id %}" method=post>
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <input type="submit" value="Add comment">
    </p>
</form>

templates/pagination.html
<div>
    <span>
        {% if page.has_previous %}<a href="?page={{ page.previous_page_number }}">&laquo; Previous</a>{% endif %}
        <span>
            Page {{ page.number }} of {{ page.paginator.num_pages }}
            ({{ page.paginator.count }} total posts)
        </span>
        {% if page.has_next %}<a href="?page={{ page.next_page_number }}">Next &raquo;</a>{% endif %}
    </span>
</div>